sudo: required
services:
  - docker
language: go
go:
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker run --rm -v "$PWD":/go/src/github.com/jstorer/gannett -w /go/src/github.com/jstorer/gannett iron/go:dev go build -o supermarket
  - docker build -t jstorer/gannett .
  - docker ps -a
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push jstorer/gannett

notifications:
  email:
    - jeremyjstorer@gmail.com