sudo: required


services:
  - docker

language: go

go:
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

after_success:
  - docker build -t jstorer/gannett .
  - docker ps -a
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push jstorer/gannett

notifications:
  email:
    - jeremyjstorer@gmail.com