sudo: required
services:
  - docker
language: go
go:
  - master

before_install:
  - docker run --rm -v "$PWD":/go/src/github.com/jstorer/gannett -w /go/src/github.com/jstorer/gannett iron/go:dev go build -o supermarket
  - docker build -t jstorer/gannett .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --pasword-stdin
  - docker push jstorer/gannett

notifications:
  email:
    - jeremyjstorer@gmail.com